// Package spreadsheets provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package spreadsheets

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// SpreadsheetRow defines model for SpreadsheetRow.
type SpreadsheetRow = []string

// SpreadsheetRows defines model for SpreadsheetRows.
type SpreadsheetRows struct {
	Rows []SpreadsheetRow `json:"rows"`
}

// PostSheetsSheetRowsJSONBody defines parameters for PostSheetsSheetRows.
type PostSheetsSheetRowsJSONBody struct {
	Columns SpreadsheetRow `json:"columns"`
}

// PostSheetsSheetRowsJSONRequestBody defines body for PostSheetsSheetRows for application/json ContentType.
type PostSheetsSheetRowsJSONRequestBody PostSheetsSheetRowsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSheetsSheetRows request
	GetSheetsSheetRows(ctx context.Context, sheet string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSheetsSheetRows request with any body
	PostSheetsSheetRowsWithBody(ctx context.Context, sheet string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSheetsSheetRows(ctx context.Context, sheet string, body PostSheetsSheetRowsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSheetsSheetRows(ctx context.Context, sheet string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSheetsSheetRowsRequest(c.Server, sheet)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSheetsSheetRowsWithBody(ctx context.Context, sheet string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSheetsSheetRowsRequestWithBody(c.Server, sheet, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSheetsSheetRows(ctx context.Context, sheet string, body PostSheetsSheetRowsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSheetsSheetRowsRequest(c.Server, sheet, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetSheetsSheetRowsRequest generates requests for GetSheetsSheetRows
func NewGetSheetsSheetRowsRequest(server string, sheet string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sheet", runtime.ParamLocationPath, sheet)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sheets/%s/rows", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSheetsSheetRowsRequest calls the generic PostSheetsSheetRows builder with application/json body
func NewPostSheetsSheetRowsRequest(server string, sheet string, body PostSheetsSheetRowsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSheetsSheetRowsRequestWithBody(server, sheet, "application/json", bodyReader)
}

// NewPostSheetsSheetRowsRequestWithBody generates requests for PostSheetsSheetRows with any type of body
func NewPostSheetsSheetRowsRequestWithBody(server string, sheet string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sheet", runtime.ParamLocationPath, sheet)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sheets/%s/rows", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetSheetsSheetRows request
	GetSheetsSheetRowsWithResponse(ctx context.Context, sheet string, reqEditors ...RequestEditorFn) (*GetSheetsSheetRowsResponse, error)

	// PostSheetsSheetRows request with any body
	PostSheetsSheetRowsWithBodyWithResponse(ctx context.Context, sheet string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSheetsSheetRowsResponse, error)

	PostSheetsSheetRowsWithResponse(ctx context.Context, sheet string, body PostSheetsSheetRowsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSheetsSheetRowsResponse, error)
}

type GetSheetsSheetRowsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SpreadsheetRows
}

// Status returns HTTPResponse.Status
func (r GetSheetsSheetRowsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSheetsSheetRowsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSheetsSheetRowsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostSheetsSheetRowsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSheetsSheetRowsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetSheetsSheetRowsWithResponse request returning *GetSheetsSheetRowsResponse
func (c *ClientWithResponses) GetSheetsSheetRowsWithResponse(ctx context.Context, sheet string, reqEditors ...RequestEditorFn) (*GetSheetsSheetRowsResponse, error) {
	rsp, err := c.GetSheetsSheetRows(ctx, sheet, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSheetsSheetRowsResponse(rsp)
}

// PostSheetsSheetRowsWithBodyWithResponse request with arbitrary body returning *PostSheetsSheetRowsResponse
func (c *ClientWithResponses) PostSheetsSheetRowsWithBodyWithResponse(ctx context.Context, sheet string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSheetsSheetRowsResponse, error) {
	rsp, err := c.PostSheetsSheetRowsWithBody(ctx, sheet, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSheetsSheetRowsResponse(rsp)
}

func (c *ClientWithResponses) PostSheetsSheetRowsWithResponse(ctx context.Context, sheet string, body PostSheetsSheetRowsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSheetsSheetRowsResponse, error) {
	rsp, err := c.PostSheetsSheetRows(ctx, sheet, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSheetsSheetRowsResponse(rsp)
}

// ParseGetSheetsSheetRowsResponse parses an HTTP response from a GetSheetsSheetRowsWithResponse call
func ParseGetSheetsSheetRowsResponse(rsp *http.Response) (*GetSheetsSheetRowsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSheetsSheetRowsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SpreadsheetRows
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSheetsSheetRowsResponse parses an HTTP response from a PostSheetsSheetRowsWithResponse call
func ParsePostSheetsSheetRowsResponse(rsp *http.Response) (*PostSheetsSheetRowsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSheetsSheetRowsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
