// Package files provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package files

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// PutFilesFileIdContentTextBody defines parameters for PutFilesFileIdContent.
type PutFilesFileIdContentTextBody = string

// PutFilesFileIdContentTextRequestBody defines body for PutFilesFileIdContent for text/plain ContentType.
type PutFilesFileIdContentTextRequestBody = PutFilesFileIdContentTextBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetFiles request
	GetFiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFilesFileIdContent request
	GetFilesFileIdContent(ctx context.Context, fileId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutFilesFileIdContent request with any body
	PutFilesFileIdContentWithBody(ctx context.Context, fileId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutFilesFileIdContentWithTextBody(ctx context.Context, fileId string, body PutFilesFileIdContentTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetFiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFilesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetFilesFileIdContent(ctx context.Context, fileId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFilesFileIdContentRequest(c.Server, fileId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFilesFileIdContentWithBody(ctx context.Context, fileId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFilesFileIdContentRequestWithBody(c.Server, fileId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFilesFileIdContentWithTextBody(ctx context.Context, fileId string, body PutFilesFileIdContentTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFilesFileIdContentRequestWithTextBody(c.Server, fileId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetFilesRequest generates requests for GetFiles
func NewGetFilesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFilesFileIdContentRequest generates requests for GetFilesFileIdContent
func NewGetFilesFileIdContentRequest(server string, fileId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "file_id", runtime.ParamLocationPath, fileId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files/%s/content", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutFilesFileIdContentRequestWithTextBody calls the generic PutFilesFileIdContent builder with text/plain body
func NewPutFilesFileIdContentRequestWithTextBody(server string, fileId string, body PutFilesFileIdContentTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPutFilesFileIdContentRequestWithBody(server, fileId, "text/plain", bodyReader)
}

// NewPutFilesFileIdContentRequestWithBody generates requests for PutFilesFileIdContent with any type of body
func NewPutFilesFileIdContentRequestWithBody(server string, fileId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "file_id", runtime.ParamLocationPath, fileId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files/%s/content", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetFiles request
	GetFilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFilesResponse, error)

	// GetFilesFileIdContent request
	GetFilesFileIdContentWithResponse(ctx context.Context, fileId string, reqEditors ...RequestEditorFn) (*GetFilesFileIdContentResponse, error)

	// PutFilesFileIdContent request with any body
	PutFilesFileIdContentWithBodyWithResponse(ctx context.Context, fileId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFilesFileIdContentResponse, error)

	PutFilesFileIdContentWithTextBodyWithResponse(ctx context.Context, fileId string, body PutFilesFileIdContentTextRequestBody, reqEditors ...RequestEditorFn) (*PutFilesFileIdContentResponse, error)
}

type GetFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Files []string `json:"files"`
	}
}

// Status returns HTTPResponse.Status
func (r GetFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetFilesFileIdContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetFilesFileIdContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFilesFileIdContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutFilesFileIdContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutFilesFileIdContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutFilesFileIdContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetFilesWithResponse request returning *GetFilesResponse
func (c *ClientWithResponses) GetFilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFilesResponse, error) {
	rsp, err := c.GetFiles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFilesResponse(rsp)
}

// GetFilesFileIdContentWithResponse request returning *GetFilesFileIdContentResponse
func (c *ClientWithResponses) GetFilesFileIdContentWithResponse(ctx context.Context, fileId string, reqEditors ...RequestEditorFn) (*GetFilesFileIdContentResponse, error) {
	rsp, err := c.GetFilesFileIdContent(ctx, fileId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFilesFileIdContentResponse(rsp)
}

// PutFilesFileIdContentWithBodyWithResponse request with arbitrary body returning *PutFilesFileIdContentResponse
func (c *ClientWithResponses) PutFilesFileIdContentWithBodyWithResponse(ctx context.Context, fileId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFilesFileIdContentResponse, error) {
	rsp, err := c.PutFilesFileIdContentWithBody(ctx, fileId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFilesFileIdContentResponse(rsp)
}

func (c *ClientWithResponses) PutFilesFileIdContentWithTextBodyWithResponse(ctx context.Context, fileId string, body PutFilesFileIdContentTextRequestBody, reqEditors ...RequestEditorFn) (*PutFilesFileIdContentResponse, error) {
	rsp, err := c.PutFilesFileIdContentWithTextBody(ctx, fileId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFilesFileIdContentResponse(rsp)
}

// ParseGetFilesResponse parses an HTTP response from a GetFilesWithResponse call
func ParseGetFilesResponse(rsp *http.Response) (*GetFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Files []string `json:"files"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetFilesFileIdContentResponse parses an HTTP response from a GetFilesFileIdContentWithResponse call
func ParseGetFilesFileIdContentResponse(rsp *http.Response) (*GetFilesFileIdContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFilesFileIdContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutFilesFileIdContentResponse parses an HTTP response from a PutFilesFileIdContentWithResponse call
func ParsePutFilesFileIdContentResponse(rsp *http.Response) (*PutFilesFileIdContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutFilesFileIdContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
